/// Immutable snapshot of quantitative results from a [VerificationSession].
///
/// [SessionSummary] is populated once verification completes and attached to
/// the session as an optional field. It is a pure value object — it carries
/// numbers, not interpretation or decision logic.
///
/// Future extension points (not yet implemented):
/// - formal verification property counts
/// - waveform file paths
/// - lint rule hit counts
class SessionSummary {
  /// Number of distinct RTL modules discovered in [VerificationSession.rtlSource].
  final int rtlModules;

  /// Total number of diagnostics emitted across all verification tools.
  final int diagnosticCount;

  /// Number of repair candidates generated by the repair planning subsystem.
  final int repairCount;

  /// Aggregate statement-level coverage as a percentage (0.0 – 100.0).
  final double coveragePercent;

  const SessionSummary({
    required this.rtlModules,
    required this.diagnosticCount,
    required this.repairCount,
    required this.coveragePercent,
  });

  /// Returns a copy with selected fields replaced.
  SessionSummary copyWith({
    int? rtlModules,
    int? diagnosticCount,
    int? repairCount,
    double? coveragePercent,
  }) {
    return SessionSummary(
      rtlModules: rtlModules ?? this.rtlModules,
      diagnosticCount: diagnosticCount ?? this.diagnosticCount,
      repairCount: repairCount ?? this.repairCount,
      coveragePercent: coveragePercent ?? this.coveragePercent,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          rtlModules == other.rtlModules &&
          diagnosticCount == other.diagnosticCount &&
          repairCount == other.repairCount &&
          coveragePercent == other.coveragePercent;

  @override
  int get hashCode =>
      Object.hash(rtlModules, diagnosticCount, repairCount, coveragePercent);
}
